const fs = require("fs");
const path = require("path");
const defaultConfig = {
  includeExt: [
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".html",
    ".css",
    ".scss",
    ".json",
    ".md",
    ".py",
    ".rb",
    ".java",
    ".kt",
    ".cs",
    ".php",
    ".go",
    ".rs",
    ".swift",
    ".c",
    ".cpp",
    ".h",
    ".hpp",
    ".sh",
    ".bash",
    ".yml",
    ".yaml",
    ".sql",
    ".xml",
    ".toml",
    ".lua",
    ".pl",
    ".dart",
    ".ex",
    ".exs",
    ".r",
    ".scala",
    "Dockerfile",
    ".gitignore",
    ".gitattributes",
  ],
  ignoreDirs: [
    "node_modules",
    ".git",
    ".vscode",
    "dist",
    "build",
    "coverage",
    ".next",
    ".idea",
    "venv",
  ],
  ignoreFiles: [
    "package-lock.json",
    "yarn.lock",
    "npm-debug.log",
    ".DS_Store",
    ".env",
    ".env.local",
  ],
  ignoreExt: [
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".bmp",
    ".tiff",
    ".ico",
    ".svg",
    ".webp",
    ".mp4",
    ".mov",
    ".avi",
    ".wmv",
    ".mp3",
    ".wav",
    ".ogg",
    ".zip",
    ".tar",
    ".gz",
    ".rar",
    ".7z",
    ".pdf",
    ".doc",
    ".docx",
    ".xls",
    ".xlsx",
    ".ppt",
    ".pptx",
    ".exe",
    ".dll",
    ".so",
    ".o",
    ".a",
    ".lib",
    ".jar",
    ".war",
    ".class",
    ".pyc",
    ".pyd",
    ".lock",
    ".db",
    ".sqlite",
    ".sqlite3",
    ".bak",
    ".tmp",
    ".swp",
    ".safetensors",
    ".pth",
    ".onnx",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".pak",
    ".bin",
    ".dat",
  ],
  ignorePatterns: [
    "**/__pycache__/**",
    "**/assets/**",
    "**/static/**",
    "**/vendor/**",
    "**/release/**",
    "**/outputs/**",
    "**/models/**",
    "**/data/**",
    "**/weights/**",
    "**/loras/**",
    "**/bin/**",
    "**/obj/**",
    "**/target/**",
    "**/.terragrunt-cache/**",
  ],
};
function loadConfig() {
  const configPath = path.join(process.cwd(), ".aiconfig.json");
  if (fs.existsSync(configPath)) {
    try {
      const userConfig = JSON.parse(fs.readFileSync(configPath, "utf8"));
      const mergedConfig = {
        includeExt: userConfig.includeExt || defaultConfig.includeExt,
        ignoreDirs: [
          ...new Set([
            ...defaultConfig.ignoreDirs,
            ...(userConfig.ignoreDirs || []),
          ]),
        ],
        ignoreFiles: [
          ...new Set([
            ...defaultConfig.ignoreFiles,
            ...(userConfig.ignoreFiles || []),
          ]),
        ],
        ignoreExt: [
          ...new Set([
            ...defaultConfig.ignoreExt,
            ...(userConfig.ignoreExt || []),
          ]),
        ],
        ignorePatterns: [
          ...new Set([
            ...defaultConfig.ignorePatterns,
            ...(userConfig.ignorePatterns || []),
          ]),
        ],
      };
      return mergedConfig;
    } catch (error) {
      console.error("Error reading or parsing .aiconfig.json:", error);
      return defaultConfig;
    }
  }
  return defaultConfig;
}
module.exports = { loadConfig };
